### ISSUE TITLE
nginx_cfg_prepend missing in nginx class

### ISSUE THREAD

**Issue by strarsis** [voxpupuli/puppet-nginx#771] opened 2016-02-24 20:55 UTC
While defined in nginx::config and its template, nginx_cfg_prepend is not available in the nginx class.
Do I have to use it differently then? - Why?

With best regards

**Comment by wyardley** [comment] 2016-10-08 07:56
If I'm not mistaken, this is by design? Configs that relate to the configuration of nginx itself (vs. setting up the class) were moved at one point to `nginx::config`. We may yet change the way the namespaces are laid out, but for now, I think this is intentional.

**Comment by wyardley** [comment] 2016-10-27 17:57
We are considering moving everything back to top level; stay tuned. For now, I'm going to close this, though.

**Closed** 2016-10-27 17:58 UTC
Labels: feature
