### ISSUE TITLE
Looking for Maintainer

### ISSUE THREAD

**Issue by jfryman** [voxpupuli/puppet-nginx#844] opened 2016-08-01 15:51 UTC
Hello everyone,

I am looking for a maintainer for this module. For a multitude of reasons, I have come to the understanding that it is time for me to let this thing go.

I've been staring at this repo, and eagerly tried to work up the energy to tackle some issues or to finish this almost two year long refactor I've been "working on". But, each time I do, I just don't have it in me. I'm exhausted by the time that I get home from work, and I cannot properly care for this module as it should be cared for.

I'm burnt. Quite hard. It has been a very long and tough 36 months for me both personally and professionally.

To that end, I would like to hand this over to someone who would like to take ownership of it. @3flex has done a wonderful job maintaining this module over the years. @3flex if you want it, it's yours. We can transfer ownership, and I'll step out of the way. If not, we'll find a good home for this. But, consider this a formal ask for new leader for this module.

For all of you who have used this module, thanks for your support and I hope you continue to find value from it. I hope to see some of you around.

:heart:

@jfryman

**Comment by 3flex** [comment] 2016-08-02 17:34
@jfryman I'd firstly like to thank you for the faith you've placed in me, and to offer me the role of maintainer for this module. I hope that freeing yourself of some of these responsibilities will help.

When I started contributing I was mainly doing it to keep myself entertained while between jobs (I'd just relocated overseas and was searching for work) and found it to be a great opportunity to teach myself git & rspec (and automated testing in general), to make some kind of meaningful open source contribution and of course to gain a deeper appreciation for and understanding of nginx :)

I feel I can claim credit for many improvements in this module, and am proud of what I've accomplished. I also hope I didn't make too many mistakes along the way!

That said, my level of contribution has dropped sharply since that initial burst of activity, and I don't feel it's appropriate for me to take ownership. I have lots of ideas for improvement but am honestly unlikely to find the time or motivation in the near future to implement them, and it wouldn't be fair to users of this module to have to wait on me alone to perform QA on PRs or let issues languish for sometimes months on end.

I think this is exactly the type of problem @voxpupuli was designed to solve! Transferring the module to them is what I'd do in your position. The module would benefit greatly from some of the tooling they've implemented, and it will receive the care it deserves from a much larger team of collaborators. I'd like to be a "module contributor" (in their words) meaning I'd still have commit and merge access, but the benefit is that when I'm unavailable there are many others who can pick up the slack.

There's some good background about @voxpupuli and what they do at  https://voxpupuli.org/blog/2016/06/10/voxpupuli-opensource-speedtrain/

All the best @jfryman!

**Comment by andrewwippler** [comment] 2016-08-05 18:21
I am an avid user of nginx and have fallen in love with this module - I use it regularly. I can understand the life balance difficulty you are going through and how you feel burnt out from a long 36 month stretch. I agree that you need a break and should step away for awhile.

I am willing to step in as maintainer of this module and your selinux module provided the following conditions are met:

- We keep the modules under your name. You made them what they are today and it should reflect that. This will also help current module users as they would not have to migrate to the new name.
- You get some rest and a vacation.
- You will reconsider maintaining the modules again after 4-6 months of rest. (It is ok for you to say no)
- I will relinquish maintainership to you if you want it back.

My qualifications:
- Puppet Certified
- LFCS (Soon to be LFCE)
- User of nginx
- User of FOSS since 1999

Here is where I can improve:
- Documentation
- Tests
- Achieving 5.0 quality score on the module

**Comment by 3flex** [comment] 2016-08-05 19:42
@jfryman I've created a PR at https://github.com/jfryman/puppet-nginx/pull/849 which will aid the migration to vox pupuli if that's the direction you choose to go.

**Comment by astrostl** [comment] 2016-08-06 00:39
This is why Vox Pupuli exists. Seems like a good call.

Maybe Andrew could join them and make it a twofer?

**Comment by jfryman** [comment] 2016-08-15 17:54
Thanks everyone. I think moving to Vox is the right move. Just need to figure out what needs to happen, and carve out time to do that.

**Comment by astrostl** [comment] 2016-08-15 18:01
FWIW, I'd just go to their IRC channel and say, "uncle"

**Comment by 3flex** [comment] 2016-08-15 19:22
See https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli

I can handle all of this for you, though my access level on this repository likely has to be increased so I can do the transfer (I won't have the rights otherwise).

I think I've done the hard part with #849, everything else looks very straightforward.

**Comment by igalic** [comment] 2016-08-29 15:12
hi people o/~

hello and and early (or perhaps late?) welcome to @voxpupuli!

most of the modules we get are just thrown over the wall, and *then* cleaned up.
We have quite a bit of practice in the latter so don't worry or shy away from doing that.

Please let us know who of you to add to the admin team for the initial transfer.

**Comment by bastelfreak** [comment] 2016-08-29 15:12
Hai!
I'm one of the Vox Pupuli members. We would be very happy to maintain this module. Just ping us on IRC 24/7 and we will fiddle out the details.

**Comment by 3flex** [comment] 2016-08-29 19:37
I've merged #849. It's a massive changeset but only affects 3 manifest files, see https://github.com/voxpupuli/puppet-nginx/pull/849/files#diff-3bfa339c375e139166a7afc6cb8c5b62

I don't think anything in there would be controversial and hopefully makes the process a bit smoother. Will still need @jfryman to pull a few levers to get this move going.

**Comment by nibalizer** [comment] 2016-08-29 19:38
@andrewwippler re: attribution
When we migrate a module to voxpupuli, we often put a note about authorship in the Readme, thanking the original author for creating the module. This isn't as flashy as keeping it in the author's namespace, but is one way we try to preserve the credit that @jfryman and others clearly deserve. 

If you have other ideas on how we can thank and credit these original authors, I'd be very interested.

And as others have stated, you're very welcome in voxpupuli!

**Comment by jfryman** [comment] 2016-08-29 19:43
@3flex You should see the levels being pulled. I'm in the IRC room chatting with the team now. This module has been transferred to their namespace. The team is working on uploading to the forge, and once that has been updated I'll deprecate my module on the forge with the `999.999.999` version and a link to the new group.

To the @voxpupuli/collaborators team: thanks for existing, and for offering to curate this module.

I'll close this issue out once the final push is done.

**Comment by cyberious** [comment] 2016-08-29 19:47
@jfryman thanks for you long work on this, we are heavy users of it and as a Voxilpupuli member I would be happy to chime in on PR's but, like you, I have no energy by the time I get home.

**Comment by 3flex** [comment] 2016-08-29 20:03
Just want to mention that I hope to still have commit access after the move!

**Comment by roidelapluie** [comment] 2016-08-29 20:04
@3flex yes you do

**Comment by bastelfreak** [comment] 2016-08-29 20:19
Hai @3flex, I sent you a github invitation to be part of the voxpupuli collaborators group, which will grant to access to our modules. Join us on IRC if you have any questions.

**Comment by raphink** [comment] 2016-08-29 21:00
Happy to see @voxpupuli being put to good use again. It's great when a maintainer is able to step aside while being sure that their work will be well taken care of.

**Comment by bbriggs** [comment] 2016-08-29 21:46
That's why we're here :)

**Closed** 2016-09-28 19:44 UTC
