### ISSUE TITLE
Hiera lookup

### ISSUE THREAD

**Issue by PierreR** [voxpupuli/puppet-nginx#536] opened 2014-12-23 11:20 UTC
I have spent a couple of hours to migrate our config to use hiera as indicated by https://github.com/jfryman/puppet-nginx/blob/master/docs/hiera.md

While I am testing this, I see no param change when I use `nginx::config::parameterx`.

Here is an example:

```
nginx::config::client_max_body_size: '100m'
nginx::config::worker_processes: 2
```
using:
```
class { 'nginx':
}
```
Of course It works when I use:
```
class { 'nginx':
  worker_processes => 2
}
```

Note also that if I use in hiera:
```
nginx::worker_processes: 2
```
then it works ...

Am I missing something ?

I am using the latest tag `0.2.1` and puppet 3.7.3

Thanks for your help.

**Comment by PierreR** [comment] 2015-01-21 15:56
@jfryman  I have tried your suggestion:
```
  class { 'nginx': }
  include nginx::config

  nginx::resource::upstream { $upstream:
    members => ['localhost:7990', ],
  }

  nginx::resource::vhost { $vhosts:
    proxy   => "http://${upstream}",
  }
```
But I get this complain from [language-puppet](https://github.com/bartavelle/language-puppet) :
```
Can't include class nginx::config twice when using the resource-like syntax (first occurence at # "./modules/nginx/manifests/init.pp" (line 217, column 13)) at # "./modules/application/manifests/profile/stash.pp" (line 10, column 3)
```
What wrong with using `nginx::worker_processes: 2` instead of `nginx::config::worker_processes: 2`

Thanks for your help.

**Comment by Hufschmidt** [comment] 2015-07-03 14:50
@PierreR Was having the same issue. The problem is that you need to make sure that "your" settings for the nginx::config class are proccessed before nginx is evaluated/compiled, because it includes its own nginx::config class (from parameters given to the nginx-class) IFF its non is defined.

The problem is you cannot do Class['nginx::config'] -> Class['nginx'] because this would lead to a cyclic dependency.
Because inside init.pp:
    Class['::nginx::package'] -> Class['::nginx::config'] ~> Class['::nginx::service']
    [...]
    anchor{ 'nginx::begin':
        before => Class['::nginx::package'],
        notify => Class['::nginx::service'],
      }

Luckily this also "contains" the solution for the ordering problem:
      Anchor['nginx::begin']
      ->
      class { 'nginx::config' :
        confd_purge   => true,
        vhost_purge   => true,
      }
      class { 'nginx' :
        manage_repo   => false,
      }
This SHOULD work, at least this seems to have fixed the problem for me.
It guarantees the correct order on "instantiation" if my head isn't totally messed now.

**Comment by PierreR** [comment] 2015-08-10 16:06
I think  #655 is related.

Does it need to be that messy ? I am currently using hiera (same as #655) and the notice message is rather off.

On the other hand, I don't want to start messing with `Anchor` in client (user not lib) code as suggested by @Hufschmidt  . I don't really understand why setting params needs to be so convoluted ;-)

**Comment by PierreR** [comment] 2015-08-10 17:54
@Hufschmidt  I have tried your suggestion trick but I have got (with puppet apply)
```
Error: Duplicate declaration: Class[Nginx::Config] is already declared in file /puppet/modules/nginx/manifests/init.pp:287; cannot redeclare at /puppet/modules/application/manifests/profile/localproxy.pp:19 on node a5e9ba79bf86.la
```

**Comment by 3flex** [comment] 2015-08-10 22:00
@PierreR unfortunately the `defined` function used in init.pp to determine whether the `nginx::config` class has been declared yet is parse order dependent.

@jfryman can you weigh in here? Looks like people either MUST use hiera, or will have to find another way to make their personal class declaration get parsed before this module's init.pp. Or the module will need to be adjusted so the solution is more robust.

**Comment by Hufschmidt** [comment] 2015-08-11 06:26
@PierreR Yes my bad, I'm actually using

      Anchor['nginx::begin']
      ->
      class { 'nginx::config' :
        confd_purge   => true,
        vhost_purge   => true,
      }

      class { 'nginx' :
        manage_repo   => false,
      }

myself...

I'll make a PR for hiera.md...

**Comment by jfryman** [comment] 2015-08-11 16:06
The `Anchor` is certainly non-ideal, and not the behavior I intended. For now, the doc update that @Hufschmidt made (thanks!) is merged to have *something*, but there needs to be a better solution.

**Comment by PierreR** [comment] 2015-08-12 06:34
As a note following #655 I have checked again with the latest source (puppet 3.8) and to my surprise `nginx::config::worker_processes: 2` in hiera does work (so it seems) without using any extra `nginx::config` declaration . This is quite ideal. I will check if this behavior is deterministic.

**Comment by wyardley** [comment] 2016-10-08 07:43
It seems like the initial issue is resolved now, and the (ugly) anchor pattern is documented, so I'm going to close this one, though lots of interesting discussion / background in here.

**Closed by wyardley** 2016-10-08 07:43 UTC
